#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Wappr\Doap\Deploy;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Deploy);
$application->run();
